cam_model: Pinhole
cam_width: 752
cam_height: 480
cam_fx: 4.250258563372763e+02
cam_fy: 4.267976260903337e+02
cam_cx: 3.860151866550880e+02
cam_cy: 2.419130336743440e+02
cam_d0: -0.288105327549552
cam_d1: 0.074578284234601
cam_d2: 7.784489598138802e-04
cam_d3: -2.277853975035461e-04